name: Build OpenIM Servers and Push Docker image to aws registries

on:
  push:
    branches:
      - release-*

  release:
    types: [published]

  workflow_dispatch:
    inputs:
      servicename:
        description: '服务名'
        required: true
        # 开发者维护 具体服务名
        default: 'openim-api'
        type: choice
        options:
          - openim-api
          - openim-push
          - openim-msgtransfer
          - openim-msggateway
          - openim-rpc-auth
          - openim-rpc-conversation
          - openim-rpc-friend
          - openim-rpc-group
          - openim-rpc-msg
          - openim-rpc-third
          - openim-rpc-user
          - openim-crontask
          - openim-cmdutils
      tag:
        description: "Tag version to be used for Docker image"
        required: true
        default: "v3.8.0"
        
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

env:
  #   GO_VERSION: "1.21"
  AWS_REGION: ap-southeast-1
  ECR_REGISTRY: 024905375334.dkr.ecr.ap-southeast-1.amazonaws.com
  SERVICE_NAME: ${{ github.event.inputs.servicename }}
  GOPROXY: https://goproxy.io,direct


jobs:
  publish-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 检出分支
        uses: actions/checkout@v4
        with:
          path: main-repo


      - name: Extract origin branch name # 发布到dev/test环境就拿分支;发布到prod环境就拿Tag
        id: extract_origin_branch
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/tags/})"

      - name: Extract branch name # 处理斜杠
        id: extract_branch
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${{ steps.extract_origin_branch.outputs.branch }} | sed 's/\//_/g')" 

      - name: Extract github sha # 拿github sha 并截取10位
        id: extract_github_sha
        shell: bash
        run: |
          echo "##[set-output name=githubsha;]$(echo ${GITHUB_SHA:0:10})"

      - name: Extract image tag # 提取镜像tag 命名规则 [分支名/Tag]_[GithubCommitSHA]
        id: extract_image_tag
        shell: bash
        run: |
          echo "##[set-output name=imagetag;]$(echo ${{ env.SERVICE_NAME }}-${{ github.event.inputs.tag }})" 
        
        # hash steps.extract_branch.outputs.branch-${{ steps.extract_github_sha.outputs.githubsha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for Docker #  (tags, labels) 
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            ${{ env.ECR_REGISTRY}}/openim

      #aws ecr login
      - name: Configure AWS credentials # 配置aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::024905375334:role/github-actions
          role-session-name: github_action_Session
          aws-region: ${{ env.AWS_REGION }}

      #- name: Login to Amazon ECR # 登录ECR
      #  id: login-ecr
      #  uses: aws-actions/amazon-ecr-login@v1

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ECR_REGISTRY}}
        
      # - name: Build, tag, and push docker image to Amazon ECR
      #  env:
      #    REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #    REPOSITORY: openim
      #    IMAGE_TAG: ${{ steps.extract_image_tag.outputs.imagetag }}
      #  run: |
      #    docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
      #    docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ./main-repo
          file: ./main-repo/build/images/${{ env.SERVICE_NAME }}/Dockerfile #dockfile for server
          push: true
          platforms: linux/amd64,linux/arm64
          # tags: openim:${{ steps.extract_image_tag.outputs.imagetag }}
          tags: $ECR_REGISTRY/openim:${{ steps.extract_image_tag.outputs.imagetag }}
          labels: ${{ env.SERVICE_NAME }}
        env:
          GOPROXY: https://goproxy.io,direct
  
      # - name: Build, tag, and push image to Amazon ECR # 构建镜像,推送镜像到ecr仓库
        # id: build-image
        # uses: docker/build-push-action@v5
        #run: |
        #  docker build -t $ECR_REGISTRY/openim:${{ steps.extract_image_tag.outputs.imagetag }} -f build/images/${{ env.SERVICE_NAME }}/Dockerfile .
        #  docker push $ECR_REGISTRY/openim:${{ steps.extract_image_tag.outputs.imagetag }}



      